# Generated by Django 5.2.12 on 2026-04-01 12:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('records', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='records', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='record',
            index=models.Index(fields=['type', 'date'], name='records_rec_type_85bb92_idx'),
        ),
        migrations.AddIndex(
            model_name='record',
            index=models.Index(fields=['category'], name='records_rec_categor_3e4a25_idx'),
        ),
        migrations.AddIndex(
            model_name='record',
            index=models.Index(fields=['created_by', 'date'], name='records_rec_created_bef7b4_idx'),
        ),
    ]
